version: '1.0'

services:

  backend:
    image: stepanti/real-time-forum-backend:latest
    ports:
      - 8080:8080
    environment:
        - BACKEND_HOST="https://localhost:3000"

  frontend:
    image: stepanti/real-time-forum-frontend:latest
    ports:
      - 3000:443
    depends_on:
      - backend
    environment:
        - FRONTEND_HOST="https://localhost:8080"